# Site settings
title: Audubon Core
description: Website for the Audubon Core standard.
url: "https://tdwg.github.io"
baseurl: "/ac"

# Build settings
markdown: kramdown
theme: tdwg-theme-jekyll
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
