# Site settings
title: Audubon Core
description: Website for the Audubon Core standard.
url: "https://tdwg.github.io"
baseurl: "/ac"

navbar:
  left:
  - text: Terms
    menu:
    - text: Audubon Core main vocabulary
      href: termlist/
    - text: format controlled vocabulary
      href: format/
    - text: subtype controlled vocabulary
      href: subtype/
    - text: variant controlled vocabulary
      href: variant/
  - text: Guides
    menu:
    - text: Introduction
      href: introduction/
    - text: User guide
      href: guide/
    - text: Structure
      href: structure/
  right:
  - text: GitHub
    href: https://github.com/tdwg/ac

js: >-
  

# Build settings
markdown: kramdown
# theme: tdwg-theme-jekyll
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
